language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r h-springboot-webservice *
  - mkdir -p deploy
  - mv h-springboot-webservice.zip deploy/h-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY                  # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: h-spring-webservice-build               # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                                    # zip 파일 접근형식
    local_dir: deploy                               # befor_deploy에 생성한 dir
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tjrdlf08@gmail.com